/*
 * Pixel pets that ship in the market's pet packs.
 *
 * Every pet is authored as text art on a 15x15 grid: one character per pixel,
 * "." is transparent, every other character is looked up in `legend`. Each pet
 * carries three consecutive animation frames (settle, active, blink), which the
 * PixelPet component cycles through with CSS keyframes — so the previews on the
 * market page are real pixel animation, not a mockup.
 */

export type PetSprite = {
  /** Character-per-pixel frames, each 15 rows of 15 characters. */
  frames: string[][]
  /** Character to color. */
  legend: Record<string, string>
}

const T = '.'

/** Slime: settles, bounces, then blinks. */
const SLIME: PetSprite = {
  legend: { B: '#62d17f', H: '#a4efb6', S: '#2c8d4c', E: '#f1f4f8', e: '#10141b' },
  frames: [
    [
      `...............`,
      `...............`,
      `.....BBBBB.....`,
      `....BBHBBBB....`,
      `...BBHHBBBBB...`,
      `..BBBHBBBBBBB..`,
      `..BBBBBBBBBBB..`,
      `..eEBBBBBBEeB..`,
      `..eEBBBBBBEeB..`,
      `..BBBBBeeBBBB..`,
      `..BBBBBBBBBBB..`,
      `..SBBBBBBBBBS..`,
      `..SSBBBBBBBSS..`,
      `...SSSSSSSSS...`,
      `${T}${T}${T}${T}${T}${T}${T}${T}${T}${T}${T}${T}${T}${T}${T}`,
    ],
    [
      `...............`,
      `...............`,
      `...............`,
      `....BBBBBBB....`,
      `..BBBHBBBBBBB..`,
      `.BBHHHBBBBBBBB.`,
      `.BBBHBBBBBBBBB.`,
      `.eEBBBBBBBBEeB.`,
      `.eEBBBBBBBBEeB.`,
      `.BBBBBBeeBBBBB.`,
      `.BBBBBBBBBBBBB.`,
      `SBBBBBBBBBBBBBS`,
      `SSBBBBBBBBBBBSS`,
      `.SSSSSSSSSSSSS.`,
      `...............`,
    ],
    [
      `...............`,
      `......BBB......`,
      `......BBB......`,
      `.....BBBBB.....`,
      `....BBBHBBBB...`,
      `...BBHHBBBBBB..`,
      `..BBBHBBBBBBB..`,
      `..BBBBBBBBBBB..`,
      `..BBBeeeBBBBe..`,
      `..BBBeeeBBBBBB.`,
      `..BBBBBeBBBBBB.`,
      `..SBBBBBBBBBBS.`,
      `..SSBBBBBBBSS..`,
      `...SSSSSSSSS...`,
      `...............`,
    ],
  ],
}

/** Cat: stands, stretches into a strut, then blinks. */
const CAT: PetSprite = {
  legend: { T: '#54c8b6', D: '#2c7a70', C: '#a9ece0', E: '#10141b', e: '#f1f4f8', N: '#ef8f9c' },
  frames: [
    [
      `...............`,
      `..TT.......TT..`,
      `..TCT.....TCT..`,
      `..TTT.....TTT..`,
      `..TTTTTTTTTTT..`,
      `..TTeETTTEeTT..`,
      `..TTTTTNNTTTT..`,
      `..TTTTTTTTTTT..`,
      `...TTTTTTTTT...`,
      `...TTTTTTTTT...`,
      `...TTTTTTTTT...`,
      `...TT.....TT...`,
      `...TT.....TT...`,
      `..DDD.....DDD..`,
      `...............`,
    ],
    [
      `...............`,
      `..TT.......TT..`,
      `..TCT.....TCT..`,
      `..TTT.....TTT..`,
      `..TTTTTTTTTTTC.`,
      `..TTeETTTEeTTCC`,
      `..TTTTTNNTTTTCC`,
      `..TTTTTTTTTTTC.`,
      `...TTTTTTTTT...`,
      `...TTTTTTTTT...`,
      `..TTTTTTTTTTT..`,
      `..TT.......TT..`,
      `..TT.......TT..`,
      `.DDD.......DDD.`,
      `...............`,
    ],
    [
      `...............`,
      `..TT.......TT..`,
      `..TCT.....TCT..`,
      `..TTT.....TTT..`,
      `..TTTTTTTTTTT..`,
      `..TTDDTTTDDTT..`,
      `..TTTTTNNTTTT..`,
      `..TTTTTTTTTTT..`,
      `...TTTTTTTTT...`,
      `...TTTTTTTTT...`,
      `...TTTTTTTTT...`,
      `...TT.....TT...`,
      `...TT.....TT...`,
      `..DDD.....DDD..`,
      `...............`,
    ],
  ],
}

/** Dragon: breathes, spreads its wings, then blinks. */
const DRAGON: PetSprite = {
  legend: { W: '#7c5cd6', w: '#a68bee', B: '#9c7ce8', P: '#cbb8ff', S: '#4b3496', E: '#f7d774', e: '#3a2a10', F: '#ff9a3c' },
  frames: [
    [
      `...............`,
      `....W.....W....`,
      `....WW...WW....`,
      `.....WWWWW.....`,
      `....WWWWWWW....`,
      `....WWWWWWW....`,
      `...WWeEWWEeWW..`,
      `...WWWWWWWWW...`,
      `....WWWWWWW....`,
      `....WWWWWWW....`,
      `...BWWWWWWWB...`,
      `...BBWWWWWBB...`,
      `....SBBBBBS....`,
      `....FF...FF....`,
      `...............`,
    ],
    [
      `...............`,
      `....W.....W....`,
      `....WW...WW....`,
      `.....WWWWW.....`,
      `..w..WWWWW..w..`,
      `.ww.WWWWWWW.ww.`,
      `.wwwWeEWWEeWwww`,
      `.wwWWWPPWWWWww.`,
      `..wWWWWWWWWWw..`,
      `...WWWWWWWWW...`,
      `...BWWWWWWWB...`,
      `...BBWWWWWBB...`,
      `....SBBBBBS....`,
      `....FF...FF....`,
      `...............`,
    ],
    [
      `...............`,
      `....W.....W....`,
      `....WW...WW....`,
      `.....WWWWW.....`,
      `....WWWWWWW....`,
      `....WWWWWWW....`,
      `...WWSWWWWSWW..`,
      `...WWWWWWWWW...`,
      `....WWWWWWW....`,
      `....WWWWWWW....`,
      `...BWWWWWWWB...`,
      `...BBWWWWWBB...`,
      `....SBBBBBS....`,
      `....FF...FF....`,
      `...............`,
    ],
  ],
}

/** Wolf: stands, throws its head back, then blinks. */
const WOLF: PetSprite = {
  legend: { F: '#aab4c4', f: '#d5dbe4', D: '#5c6675', E: '#10141b', e: '#cfe8ff', N: '#2b3240' },
  frames: [
    [
      `...............`,
      `.....F...F.....`,
      `.....FF.FF.....`,
      `....FDFFFDF....`,
      `....FFFFFFFF...`,
      `...FFeEFFEeFF..`,
      `...FFFFFFFFFF..`,
      `....FFNNNFF....`,
      `.....FFFFFf....`,
      `....FFFFFFFF...`,
      `...FFFFFFFFF...`,
      `...FFFFFFFFF...`,
      `....FF...FF....`,
      `....DD...DD....`,
      `...............`,
    ],
    [
      `......F...F....`,
      `......FF.FF....`,
      `.....FDFFFDF...`,
      `.....FFFFFFF...`,
      `....FFeEFFEeF..`,
      `....FFFFNFFFF..`,
      `.....FFFNNNF...`,
      `......FFFFFf...`,
      `.....FFFFFFFF..`,
      `...FFFFFFFFF...`,
      `...FFFFFFFFF...`,
      `....FFF..FFF...`,
      `....FF....FF...`,
      `....DD....DD...`,
      `...............`,
    ],
    [
      `...............`,
      `.....F...F.....`,
      `.....FF.FF.....`,
      `....FDFFFDF....`,
      `....FFFFFFFF...`,
      `...FFDD...DDF..`,
      `...FFFFFFFFFF..`,
      `....FFNNNFF....`,
      `.....FFFFFf....`,
      `....FFFFFFFF...`,
      `...FFFFFFFFF...`,
      `...FFFFFFFFF...`,
      `....FF...FF....`,
      `....DD...DD....`,
      `...............`,
    ],
  ],
}

/** Wisp: hovers, flares with inner light, then blinks out. */
const WISP: PetSprite = {
  legend: { G: '#e6f4ff', g: '#9cc8ee', S: '#5f8fc4', E: '#10141b', e: '#2b6a94' },
  frames: [
    [
      `...............`,
      `.....GGGGG.....`,
      `....GGGGGGG....`,
      `...GGGGGGGGG...`,
      `...GGeEGGEeGG..`,
      `...GGGGGGGGG...`,
      `...GGGGgGGGG...`,
      `...GGGGGGGGG...`,
      `..GGGGGGGGGGG..`,
      `..gGGGGGGGGGg..`,
      `..gGgGGGGGgGg..`,
      `..S.gGgGgGg.S..`,
      `...S.S.S.S.S...`,
      `...............`,
      `...............`,
    ],
    [
      `.....GGGGG.....`,
      `....GGGGGGG....`,
      `...GGGGGGGGG...`,
      `...GGGGGGGGG...`,
      `..GGeEGGEeGGG..`,
      `..GGGGGGGGGGG..`,
      `..GGGGggGGGGG..`,
      `..GGGGGGGGGGG..`,
      `.GGGGGGGGGGGGG.`,
      `.gGGGGGGGGGGGg.`,
      `.gGgGGGGGGGgGg.`,
      `.S.gGgGGGgGg.S.`,
      `..S..S...S..S..`,
      `...............`,
      `...............`,
    ],
    [
      `...............`,
      `.....GGGGG.....`,
      `....GGGGGGG....`,
      `...GGGGGGGGG...`,
      `...GGDDGDDGGG..`,
      `...GGGGGGGGG...`,
      `...GGGGgGGGG...`,
      `...GGGGGGGGG...`,
      `..GGGGGGGGGGG..`,
      `..gGGGGGGGGGg..`,
      `..gGgGGGGGgGg..`,
      `..S.gGgGgGg.S..`,
      `...S.S.S.S.S...`,
      `...............`,
      `...............`,
    ],
  ],
}

/** Mushroom: rests, hops, then blinks. */
const MUSHROOM: PetSprite = {
  legend: { R: '#e0574f', r: '#f28b83', W: '#fdf3e2', M: '#a63c38', C: '#f6e2c0', E: '#10141b', e: '#f1f4f8' },
  frames: [
    [
      `...............`,
      `.....RRRRR.....`,
      `...RRrrRRRRR...`,
      `..RWWRRRRWWRR..`,
      `..RRRRRRRRRRR..`,
      `.RRRRRWWRRRRRR.`,
      `.MRRRRRRRRRRRM.`,
      `..MMMMMMMMMMM..`,
      `....CCCCCCC....`,
      `....CCCCCCC....`,
      `....CeECCeC....`,
      `....CCCCCCC....`,
      `....CCCCCCC....`,
      `....CCCCCCC....`,
      `...............`,
    ],
    [
      `...............`,
      `...............`,
      `.....RRRRR.....`,
      `...RRrrRRRRR...`,
      `..RWWRRRRWWRR..`,
      `..RRRRRRRRRRR..`,
      `.RRRRRWWRRRRRR.`,
      `.MRRRRRRRRRRRM.`,
      `..MMMMMMMMMMM..`,
      `....CCCCCCC....`,
      `....CeECCeC....`,
      `....CCCCCCC....`,
      `....CCCCCCC....`,
      `....CCCCCCC....`,
      `...............`,
    ],
    [
      `...............`,
      `.....RRRRR.....`,
      `...RRrrRRRRR...`,
      `..RWWRRRRWWRR..`,
      `..RRRRRRRRRRR..`,
      `.RRRRRWWRRRRRR.`,
      `.MRRRRRRRRRRRM.`,
      `..MMMMMMMMMMM..`,
      `....CCCCCCC....`,
      `....CCCCCCC....`,
      `....CDDCCDC....`,
      `....CCCCCCC....`,
      `....CCCCCCC....`,
      `....CCCCCCC....`,
      `...............`,
    ],
  ],
}

/** Phoenix: perches, flares its tail, then blinks. */
const PHOENIX: PetSprite = {
  legend: { R: '#f0592b', O: '#ff9a3c', Y: '#ffd166', D: '#a8321a', E: '#10141b', e: '#3a1c10' },
  frames: [
    [
      `.......O.......`,
      `......ORO......`,
      `......RRR......`,
      `.....RRRRR.....`,
      `.....ReERR.....`,
      `.....RRRRR.....`,
      `....RRRRRRR....`,
      `...ORRRRRRRO...`,
      `...ORRRRRRRO...`,
      `...DRRRRRRRD...`,
      `....DRRRRRD....`,
      `.....RR.RR.....`,
      `.....Y...Y.....`,
      `....YY...YY....`,
      `...............`,
    ],
    [
      `......OYO......`,
      `.....OOROO.....`,
      `.....ORRRO.....`,
      `.....RRRRR.....`,
      `.....ReERR.....`,
      `.....RRRRR.....`,
      `...OYRRRRRRO...`,
      `..OORRRRRRROO..`,
      `..ORRRRRRRRRO..`,
      `..DRRRRRRRRRD..`,
      `...DRRRRRRRD...`,
      `....RR...RR....`,
      `....YY...YY....`,
      `...YY.....YY...`,
      `...............`,
    ],
    [
      `.......O.......`,
      `......ORO......`,
      `......RRR......`,
      `.....RRRRR.....`,
      `.....RDDDR.....`,
      `.....RRRRR.....`,
      `....RRRRRRR....`,
      `...ORRRRRRRO...`,
      `...ORRRRRRRO...`,
      `...DRRRRRRRD...`,
      `....DRRRRRD....`,
      `.....RR.RR.....`,
      `.....Y...Y.....`,
      `....YY...YY....`,
      `...............`,
    ],
  ],
}

export const petSprites: Record<string, PetSprite> = {
  slime: SLIME,
  cat: CAT,
  dragon: DRAGON,
  wolf: WOLF,
  wisp: WISP,
  mushroom: MUSHROOM,
  phoenix: PHOENIX,
}

export type PetId = keyof typeof petSprites
export type PetAnimationId = 'idle' | 'walk' | 'run' | 'sit' | 'sleep' | 'celebrate' | 'hurt'

/** Shared animation catalogue: the loop length is the pack spec sold in the market. */
export const PET_ANIMATIONS: Record<PetAnimationId, { duration: number }> = {
  idle: { duration: 1600 },
  walk: { duration: 900 },
  run: { duration: 500 },
  sit: { duration: 2600 },
  sleep: { duration: 3400 },
  celebrate: { duration: 700 },
  hurt: { duration: 320 },
}

/** Pet packs sold in the market. */
export type PetPackId = 'starter' | 'moonlit' | 'garden'

export const petPacks: Record<PetPackId, { pets: PetId[]; animations: PetAnimationId[] }> = {
  starter: { pets: ['slime', 'cat', 'mushroom'], animations: ['idle', 'walk', 'run', 'sit', 'sleep', 'celebrate', 'hurt'] },
  moonlit: { pets: ['dragon', 'wolf', 'wisp'], animations: ['idle', 'walk', 'run', 'sit', 'sleep', 'celebrate', 'hurt'] },
  garden: { pets: ['wisp', 'mushroom', 'phoenix'], animations: ['idle', 'walk', 'run', 'sit', 'sleep', 'celebrate', 'hurt'] },
}
